name       : scour
homepage   : http://www.codedread.com/scour/
version    : '0.35'
release    : 4
source     :
    - https://github.com/scour-project/scour/archive/v0.35.tar.gz : 91a7dd0d721a3567b802c1b353ef451621594e628fe723cedb65cd4629fbc96f
license    : Apache-2.0
component  : multimedia.graphics
summary    : Python tool for SVG optimization.
description: |
    Scour is a Python tool that takes an SVG file and produces a cleaner and more concise file. It is intended to be used after exporting to SVG with a GUI editor, such as Inkscape or Adobe Illustrator.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-setuptools
    - python-six
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
