name       : scour
version    : 0.33
release    : 2
source     :
    - https://github.com/codedread/scour/archive/v0.33.tar.gz : e9b4fb4beb653afbdbc43c4cc0836902d6f287d882b6b7cdf714c456ff0841a8
license    : Apache-2.0
component  : desktop.multimedia
summary    : Python tool for SVG optimization.
description: |
    Scour is a Python tool that takes an SVG file and produces a cleaner and more concise file. It is intended to be used after exporting to SVG with a GUI editor, such as Inkscape or Adobe Illustrator.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-setuptools
    - python-six
build      : |
    python setup.py build
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
